name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        #with:
          #source-url: https://nuget.pkg.github.com/<organization>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Build CsmlEngine and generate NuGet package
        run: |
          cd CsmlEngine
          dotnet pack -c Debug -p:PackageVersion=0.0.1-unstable${{github.run_number}} -o out
      - name: Push generated CsmlEngine package to GitHub registry
        run: dotnet nuget push ./CsmlEngine/out/*.nupkg --source https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --no-symbols true
        
      - name: Build CsmlGenerator and generate NuGet package
        run: |
          cd CsmlGenerator
          dotnet pack -c Debug -p:PackageVersion=0.0.1-unstable${{github.run_number}} -o out
      - name: Push generated CsmlGenerator package to GitHub registry
        run: dotnet nuget push ./CsmlGenerator/out/*.nupkg --source https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --no-symbols true
              
      - name: Build CsmlWeb and generate NuGet package
        run: |
          cd CsmlWeb
          dotnet pack -c Debug -p:PackageVersion=0.0.1-unstable${{github.run_number}} -o out
      - name: Push generated CsmlWeb package to GitHub registry
        run: dotnet nuget push ./CsmlWeb/out/*.nupkg --source https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --no-symbols true
