name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Version
        run: |
          export package_version="0.1.$((${{github.run_number}}))"
          echo "Package Version = $package_version"
          echo "package_version=$package_version" >> $GITHUB_ENV

      
      - name: Pack StaticSharp.Core
        run: |
          dotnet pack ./StaticSharp/StaticSharp.csproj \
          -c Release \
          -p:PackageVersion=${{env.package_version}} \
          -o _out \
          -p:ContinuousIntegrationBuild=true \
          -p:PublishRepositoryUrl=true \
          -p:EmbedUntrackedSources=true \
          -p:DebugType=embedded
       
      - name: Publish StaticSharp.Core
        run: |
          dotnet nuget push \
          ./_out/StaticSharp.Core.${{env.package_version}}.nupkg \
          -k ${{secrets.NUGET_KEY}} \
          -s https://api.nuget.org/v3/index.json
      
      - name: Pack StaticSharp.RoutingSg
        run: |
          dotnet pack ./RoutingSg/Generator/RoutingSg.csproj \
          -c Release \
          -p:PackageVersion=${{env.package_version}} \
          -o _out \
          -p:ContinuousIntegrationBuild=true \
          -p:PublishRepositoryUrl=true \
          -p:EmbedUntrackedSources=true \
          -p:DebugType=embedded
       
      - name: Publish StaticSharp.RoutingSg
        run: |
          dotnet nuget push \
          ./_out/StaticSharp.RoutingSg.${{env.package_version}}.nupkg \
          -k ${{secrets.NUGET_KEY}} \
          -s https://api.nuget.org/v3/index.json
        
      - name: Pack StaticSharp.ComponentSg
        run: |
          dotnet pack ./ComponentSg/Generator/ComponentSg.csproj \
          -c Release \
          -p:PackageVersion=${{env.package_version}} \
          -o _out \
          -p:ContinuousIntegrationBuild=true \
          -p:PublishRepositoryUrl=true \
          -p:EmbedUntrackedSources=true \
          -p:DebugType=embedded
       
      - name: Publish StaticSharp.ComponentSg
        run: |
          dotnet nuget push \
          ./_out/StaticSharp.ComponentSg.${{env.package_version}}.nupkg \
          -k ${{secrets.NUGET_KEY}} \
          -s https://api.nuget.org/v3/index.json
      
      - name: Trigger templates update
        run: |
          curl -L -i \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Authorization: Bearer ${{ secrets.PAT_REPOSITORY_DISPATCH }}" \
          -d '{"event_type":"staticsharp_core_updated","client_payload":{"package_version":"${{env.package_version}}"}}' \
          https://api.github.com/repos/StaticSharp/StaticSharpVsCodeTemplates/dispatches
        